# Generated by Django 5.2.17 on 2026-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='office_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
