# Generated by Django 5.2.17 on 2026-10-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_office_address_and_more'),
        ('accounts', '0002_vendor_verification'),
    ]

    operations = [
    ]
