# Generated by Django 5.2.17 on 2026-10-06 15:30

import django.core.validators
import django.db.models.deletion
import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStorefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=vendors.models.storefront_logo_path, validators=[vendors.models.validate_logo_size])),
                ('slogan', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,15}$', 'Enter a phone number of 7-15 digits, with an optional leading +.')])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='accounts.vendorprofile')),
            ],
        ),
    ]
