# Generated by Django 5.2.17 on 2026-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PREPARING', 'Preparing'), ('READY FOR COLLECTION', 'Ready For Collection')], default='RECEIVED', max_length=20),
        ),
    ]
