# Generated by Django 5.2.17 on 2026-10-09 14:05

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=products.models.product_image_path, validators=[products.models.validate_image_size]),
        ),
    ]
